import ChatSteamsController from '#controllers/chat_steams_controller'
import User from '#models/user'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  data = [
    {
      id: 1,
      email: 'amir.398@hotmail.fr',
      password: 'Hicsof30@',
      firstname: 'Amir',
      lastname: 'Meberbeche',
      profilImage: 'e969c50242fa5c161a9973ffb2494bad.webp',
      birthDate: new Date('1996-03-30'),
      description:
        'Développeur web passionné par le basketball, la lecture et la programmation. Originaire de Paris, mon rêve est de vivre à New York.',
      cityOfBirth: 'Paris',
      iLike: 'Jouer au basket, lire des livres, coder',
      dreamCity: 'New York',
      activity: 'Web Développeur',
      astrologicalSign: 'Bélier',
      favoriteShows: 'Game of Thrones, Breaking Bad, The Boys',
      favoriteArtists: 'Shaboozey, J Cole, Kendrick Lamar',
      centerOfInterest: 'Basketball, Livres, Dév web',
    },
    {
      id: 2,
      email: 'sophia.larue@gmail.com',
      password: 'Hicsof30@',
      firstname: 'Sophia',
      lastname: 'Larue',
      profilImage: 'p7q8r9s0t1u2v3w4x5y6z7a8b9c0d1e2.jpg',
      birthDate: new Date('1990-07-14'),
      description:
        'Sophia est une passionnée de la nature et adore explorer de nouveaux endroits. Elle aime aussi la photographie et la cuisine.',
      cityOfBirth: 'Lyon',
      iLike: 'Photographie, randonnée, cuisine',
      dreamCity: 'Tokyo',
      activity: 'Photographe',
      astrologicalSign: 'Cancer',
      favoriteShows: "Planet Earth, Chef's Table, Stranger Things",
      favoriteArtists: 'Ed Sheeran, Adele, Taylor Swift',
      centerOfInterest: 'Nature, Photographie, Cuisine',
    },
    {
      id: 3,
      email: 'lucas.martin@yahoo.com',
      password: 'Hicsof30@',
      firstname: 'Lucas',
      lastname: 'Martin',
      profilImage: 'f3g4h5i6j7k8l9m0n1o2p3q4r5s6t7u8.jpg',
      birthDate: new Date('1985-11-22'),
      description:
        "Lucas est un entrepreneur dynamique passionné par les nouvelles technologies et l'innovation. Il aime aussi le sport et les voyages.",
      cityOfBirth: 'Marseille',
      iLike: 'Innovation, sport, voyages',
      dreamCity: 'San Francisco',
      activity: 'Entrepreneur',
      astrologicalSign: 'Scorpion',
      favoriteShows: 'Silicon Valley, Shark Tank, Black Mirror',
      favoriteArtists: 'Coldplay, Imagine Dragons, U2',
      centerOfInterest: 'Technologies, Sport, Voyages',
    },
    {
      id: 4,
      email: 'emma.dubois@outlook.com',
      password: 'Hicsof30@',
      firstname: 'Emma',
      lastname: 'Dubois',
      profilImage: 'a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6.jpg',
      birthDate: new Date('1992-05-18'),
      description:
        'Emma est une artiste talentueuse qui adore peindre et dessiner. Elle aime aussi la musique et les animaux.',
      cityOfBirth: 'Nice',
      iLike: 'Peinture, dessin, musique, animaux',
      dreamCity: 'Paris',
      activity: 'Artiste',
      astrologicalSign: 'Taureau',
      favoriteShows: 'The Crown, Friends, The Office',
      favoriteArtists: 'Van Gogh, Monet, Picasso',
      centerOfInterest: 'Art, Musique, Animaux',
    },
    {
      id: 5,
      email: 'noah.lefevre@gmail.com',
      password: 'Hicsof30@',
      firstname: 'Noah',
      lastname: 'Lefevre',
      profilImage: 'v1w2x3y4z5a6b7c8d9e0f1g2h3i4j5k6.jpg',
      birthDate: new Date('1988-08-30'),
      description:
        'Noah est un musicien passionné qui adore jouer de la guitare et écrire des chansons. Il aime aussi voyager et découvrir de nouvelles cultures.',
      cityOfBirth: 'Bordeaux',
      iLike: 'Musique, guitare, voyages',
      dreamCity: 'Nashville',
      activity: 'Musicien',
      astrologicalSign: 'Vierge',
      favoriteShows: 'The Voice, American Idol, Nashville',
      favoriteArtists: 'John Mayer, Eric Clapton, Jimi Hendrix',
      centerOfInterest: 'Musique, Voyages, Culture',
    },
    {
      id: 6,
      email: 'chloe.moreau@hotmail.fr',
      password: 'Hicsof30@',
      firstname: 'Chloe',
      lastname: 'Moreau',
      profilImage: 'l7m8n9o0p1q2r3s4t5u6v7w8x9y0z1a2.jpg',
      birthDate: new Date('1995-12-12'),
      description:
        'Chloe est une danseuse professionnelle qui aime également la mode et le cinéma. Elle rêve de se produire sur les plus grandes scènes du monde.',
      cityOfBirth: 'Lille',
      iLike: 'Danse, mode, cinéma',
      dreamCity: 'Los Angeles',
      activity: 'Danseuse',
      astrologicalSign: 'Sagittaire',
      favoriteShows: 'So You Think You Can Dance, Dancing with the Stars, La La Land',
      favoriteArtists: 'Beyoncé, Rihanna, Lady Gaga',
      centerOfInterest: 'Danse, Mode, Cinéma',
    },
    {
      id: 7,
      email: 'maxime.bernard@gmail.com',
      password: 'Hicsof30@',
      firstname: 'Maxime',
      lastname: 'Bernard',
      profilImage: 'b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8.jpg',
      birthDate: new Date('1987-03-04'),
      description:
        'Maxime est un chef cuisinier qui adore expérimenter de nouvelles recettes et saveurs. Il aime aussi le jardinage et le sport.',
      cityOfBirth: 'Strasbourg',
      iLike: 'Cuisine, jardinage, sport',
      dreamCity: 'Lyon',
      activity: 'Chef cuisinier',
      astrologicalSign: 'Poissons',
      favoriteShows: "MasterChef, Top Chef, Hell's Kitchen",
      favoriteArtists: 'Gordon Ramsay, Jamie Oliver, Paul Bocuse',
      centerOfInterest: 'Cuisine, Jardinage, Sport',
    },
    {
      id: 8,
      email: 'lea.petit@yahoo.com',
      password: 'Hicsof30@',
      firstname: 'Lea',
      lastname: 'Petit',
      profilImage: 'r1s2t3u4v5w6x7y8z9a0b1c2d3e4f5g6.jpg',
      birthDate: new Date('1993-06-25'),
      description:
        'Lea est une écrivain qui aime créer des histoires captivantes. Elle adore également les voyages et la photographie.',
      cityOfBirth: 'Rennes',
      iLike: 'Écriture, voyages, photographie',
      dreamCity: 'Venise',
      activity: 'Écrivain',
      astrologicalSign: 'Cancer',
      favoriteShows: "Outlander, Game of Thrones, The Handmaid's Tale",
      favoriteArtists: 'J.K. Rowling, George R.R. Martin, J.R.R. Tolkien',
      centerOfInterest: 'Écriture, Voyages, Photographie',
    },
    {
      id: 9,
      email: 'julien.renard@outlook.com',
      password: 'Hicsof30@',
      firstname: 'Julien',
      lastname: 'Renard',
      profilImage: 'h5i6j7k8l9m0n1o2p3q4r5s6t7u8v9w0.jpg',
      birthDate: new Date('1991-01-16'),
      description:
        'Julien est un ingénieur en informatique qui aime les jeux vidéo et les nouvelles technologies. Il rêve de travailler pour une grande entreprise de jeux vidéo.',
      cityOfBirth: 'Nantes',
      iLike: 'Jeux vidéo, technologies, voyages',
      dreamCity: 'San Francisco',
      activity: 'Ingénieur en informatique',
      astrologicalSign: 'Capricorne',
      favoriteShows: 'Silicon Valley, The IT Crowd, Mr. Robot',
      favoriteArtists: 'Daft Punk, Justice, M83',
      centerOfInterest: 'Technologies, Jeux vidéo, Voyages',
    },
    {
      id: 10,
      email: 'lucie.rousseau@gmail.com',
      password: 'Hicsof30@',
      firstname: 'Lucie',
      lastname: 'Rousseau',
      profilImage: 'x7y8z9a0b1c2d3e4f5g6h7i8j9k0l1m2.jpg',
      birthDate: new Date('1994-09-29'),
      description:
        'Lucie est une passionnée de mode qui adore créer de nouvelles tenues et styles. Elle aime aussi la photographie et le design.',
      cityOfBirth: 'Montpellier',
      iLike: 'Mode, photographie, design',
      dreamCity: 'Milan',
      activity: 'Styliste',
      astrologicalSign: 'Balance',
      favoriteShows: 'Project Runway, Next in Fashion, The Bold Type',
      favoriteArtists: 'Coco Chanel, Karl Lagerfeld, Alexander McQueen',
      centerOfInterest: 'Mode, Photographie, Design',
    },
    {
      id: 11,
      email: 'pierre.robert@hotmail.fr',
      password: 'Hicsof30@',
      firstname: 'Pierre',
      lastname: 'Robert',
      profilImage: 'n3o4p5q6r7s8t9u0v1w2x3y4z5a6b7c8.jpg',
      birthDate: new Date('1986-11-11'),
      description:
        "Pierre est un passionné de sports extrêmes qui adore l'escalade, le surf et le VTT. Il aime aussi voyager et découvrir de nouveaux horizons.",
      cityOfBirth: 'Marseille',
      iLike: 'Sports extrêmes, voyages, nature',
      dreamCity: 'Sydney',
      activity: 'Instructeur de sports extrêmes',
      astrologicalSign: 'Scorpion',
      favoriteShows: 'Free Solo, The Dawn Wall, Ultimate Beastmaster',
      favoriteArtists: 'Red Hot Chili Peppers, Linkin Park, Foo Fighters',
      centerOfInterest: 'Sports extrêmes, Voyages, Nature',
    },
    {
      id: 12,
      email: 'manon.legrand@gmail.com',
      password: 'Hicsof30@',
      firstname: 'Manon',
      lastname: 'Legrand',
      profilImage: 'd9e0f1g2h3i4j5k6l7m8n9o0p1q2r3s4.jpg',
      birthDate: new Date('1992-07-07'),
      description:
        'Manon est une passionnée de cuisine qui adore expérimenter de nouvelles recettes et découvrir des saveurs exotiques.',
      cityOfBirth: 'Lille',
      iLike: 'Cuisine, voyages, jardinage',
      dreamCity: 'Tokyo',
      activity: 'Chef cuisinier',
      astrologicalSign: 'Cancer',
      favoriteShows: 'MasterChef, Top Chef, The Great British Bake Off',
      favoriteArtists: 'Jamie Oliver, Gordon Ramsay, Paul Bocuse',
      centerOfInterest: 'Cuisine, Voyages, Jardinage',
    },
    {
      id: 13,
      email: 'quentin.fournier@yahoo.com',
      password: 'Hicsof30@',
      firstname: 'Quentin',
      lastname: 'Fournier',
      profilImage: 't5u6v7w8x9y0z1a2b3c4d5e6f7g8h9i0.jpg',
      birthDate: new Date('1990-04-20'),
      description:
        'Quentin est un développeur de logiciels qui aime créer des applications innovantes. Il est passionné par la technologie et les jeux vidéo.',
      cityOfBirth: 'Toulouse',
      iLike: 'Développement de logiciels, jeux vidéo, lecture',
      dreamCity: 'San Francisco',
      activity: 'Développeur de logiciels',
      astrologicalSign: 'Bélier',
      favoriteShows: 'Silicon Valley, Mr. Robot, Black Mirror',
      favoriteArtists: 'Travis Scott, Post Malone, The Weeknd',
      centerOfInterest: 'Technologie, Jeux vidéo, Lecture',
    },
    {
      id: 14,
      email: 'camille.dumont@outlook.com',
      password: 'Hicsof30@',
      firstname: 'Camille',
      lastname: 'Dumont',
      profilImage: 'j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6.jpg',
      birthDate: new Date('1995-05-12'),
      description:
        "Camille est une artiste de talent qui aime créer des œuvres d'art uniques. Elle aime également la photographie et la nature.",
      cityOfBirth: 'Bordeaux',
      iLike: 'Art, photographie, nature',
      dreamCity: 'Paris',
      activity: 'Artiste',
      astrologicalSign: 'Taureau',
      favoriteShows: 'The Crown, Friends, The Office',
      favoriteArtists: 'Van Gogh, Monet, Picasso',
      centerOfInterest: 'Art, Photographie, Nature',
    },
    {
      id: 15,
      email: 'mathieu.brun@gmail.com',
      password: 'Hicsof30@',
      firstname: 'Mathieu',
      lastname: 'Brun',
      profilImage: 'z7a8b9c0d1e2f3g4h5i6j7k8l9m0n1o2.jpg',
      birthDate: new Date('1988-02-02'),
      description:
        'Mathieu est un passionné de cinéma qui adore regarder des films et analyser des scénarios. Il aime aussi écrire et lire.',
      cityOfBirth: 'Nantes',
      iLike: 'Cinéma, écriture, lecture',
      dreamCity: 'Los Angeles',
      activity: 'Scénariste',
      astrologicalSign: 'Verseau',
      favoriteShows: 'Breaking Bad, The Sopranos, Mad Men',
      favoriteArtists: 'Hans Zimmer, John Williams, Danny Elfman',
      centerOfInterest: 'Cinéma, Écriture, Lecture',
    },
    {
      id: 16,
      email: 'anais.blanc@hotmail.fr',
      password: 'Hicsof30@',
      firstname: 'Anais',
      lastname: 'Blanc',
      profilImage: 'p3q4r5s6t7u8v9w0x1y2z3a4b5c6d7e8.jpg',
      birthDate: new Date('1996-08-08'),
      description:
        'Anais est une passionnée de mode qui adore créer de nouvelles tenues et styles. Elle aime également la photographie et le design.',
      cityOfBirth: 'Nice',
      iLike: 'Mode, photographie, design',
      dreamCity: 'Milan',
      activity: 'Styliste',
      astrologicalSign: 'Lion',
      favoriteShows: 'Project Runway, Next in Fashion, The Bold Type',
      favoriteArtists: 'Coco Chanel, Karl Lagerfeld, Alexander McQueen',
      centerOfInterest: 'Mode, Photographie, Design',
    },
    {
      id: 17,
      email: 'florian.perrin@gmail.com',
      password: 'Hicsof30@',
      firstname: 'Florian',
      lastname: 'Perrin',
      profilImage: 'f9g0h1i2j3k4l5m6n7o8p9q0r1s2t3u4.jpg',
      birthDate: new Date('1989-10-23'),
      description:
        "Florian est un développeur web passionné par les nouvelles technologies et l'innovation. Il aime aussi le sport et les voyages.",
      cityOfBirth: 'Toulouse',
      iLike: 'Technologie, sport, voyages',
      dreamCity: 'San Francisco',
      activity: 'Développeur web',
      astrologicalSign: 'Scorpion',
      favoriteShows: 'Silicon Valley, Shark Tank, Black Mirror',
      favoriteArtists: 'Daft Punk, Justice, M83',
      centerOfInterest: 'Technologie, Sport, Voyages',
    },
    {
      id: 18,
      email: 'julie.dupont@yahoo.com',
      password: 'Hicsof30@',
      firstname: 'Julie',
      lastname: 'Dupont',
      profilImage: 'v5w6x7y8z9a0b1c2d3e4f5g6h7i8j9k0.jpg',
      birthDate: new Date('1993-11-05'),
      description:
        'Julie est une passionnée de cuisine qui adore expérimenter de nouvelles recettes et découvrir des saveurs exotiques.',
      cityOfBirth: 'Lille',
      iLike: 'Cuisine, voyages, jardinage',
      dreamCity: 'Tokyo',
      activity: 'Chef cuisinier',
      astrologicalSign: 'Scorpion',
      favoriteShows: 'MasterChef, Top Chef, The Great British Bake Off',
      favoriteArtists: 'Jamie Oliver, Gordon Ramsay, Paul Bocuse',
      centerOfInterest: 'Cuisine, Voyages, Jardinage',
    },
    {
      id: 19,
      email: 'nicolas.martinez@outlook.com',
      password: 'Hicsof30@',
      firstname: 'Nicolas',
      lastname: 'Martinez',
      profilImage: 'l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5a6.jpg',
      birthDate: new Date('1987-12-30'),
      description:
        "Nicolas est un passionné de sports extrêmes qui adore l'escalade, le surf et le VTT. Il aime aussi voyager et découvrir de nouveaux horizons.",
      cityOfBirth: 'Marseille',
      iLike: 'Sports extrêmes, voyages, nature',
      dreamCity: 'Sydney',
      activity: 'Instructeur de sports extrêmes',
      astrologicalSign: 'Capricorne',
      favoriteShows: 'Free Solo, The Dawn Wall, Ultimate Beastmaster',
      favoriteArtists: 'Red Hot Chili Peppers, Linkin Park, Foo Fighters',
      centerOfInterest: 'Sports extrêmes, Voyages, Nature',
    },
    {
      id: 20,
      email: 'amelie.thomas@gmail.com',
      password: 'Hicsof30@',
      firstname: 'Amelie',
      lastname: 'Thomas',
      profilImage: 'b7c8d9e0f1g2h3i4j5k6l7m8n9o0p1q2.jpg',
      birthDate: new Date('1994-01-14'),
      description:
        'Amelie est une passionnée de mode qui adore créer de nouvelles tenues et styles. Elle aime également la photographie et le design.',
      cityOfBirth: 'Nice',
      iLike: 'Mode, photographie, design',
      dreamCity: 'Milan',
      activity: 'Styliste',
      astrologicalSign: 'Capricorne',
      favoriteShows: 'Project Runway, Next in Fashion, The Bold Type',
      favoriteArtists: 'Coco Chanel, Karl Lagerfeld, Alexander McQueen',
      centerOfInterest: 'Mode, Photographie, Design',
    },
  ]

  async run() {
    await User.createMany(this.data)
    const chatStreamController = new ChatSteamsController()
    for (const user of this.data) {
      await chatStreamController.storeUser(user.id, user.firstname, user.lastname, user.profilImage)
    }
  }
}
