import Post from '#models/post'
import { BaseSeeder } from '@adonisjs/lucid/seeders'
import db from '@adonisjs/lucid/services/db'
export default class extends BaseSeeder {
  async run() {
    await Post.createMany([
      {
        id: 1,
        userId: 1,
        title: 'Restaurant Le Jules Verne',
        categoryId: 1,
        price: 120,
        description:
          "Dînez dans ce restaurant gastronomique avec une vue imprenable sur Paris, situé au deuxième étage de la Tour Eiffel. Profitez d'une cuisine raffinée et innovante, créée par des chefs de renom, tout en admirant la ville lumière.",
        location: 'Tour Eiffel, 2nd floor, Avenue Gustave Eiffel, 75007 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.294844 48.857739)'), 4326)"),
        latitude: 48.857739,
        longitude: 2.294844,
      },
      {
        id: 2,
        userId: 1,
        title: "Restaurant L'Atelier de Joël Robuchon",
        categoryId: 1,
        price: 150,
        description:
          "Découvrez la cuisine créative et savoureuse de Joël Robuchon dans un cadre élégant et moderne. Profitez d'un repas gastronomique inoubliable préparé avec des ingrédients de la plus haute qualité.",
        location: '5 Rue de Montalembert, 75007 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3265 48.8556)'), 4326)"),
        latitude: 48.8556,
        longitude: 2.3265,
      },
      {
        id: 3,
        userId: 1,
        title: 'Restaurant Le Cinq',
        categoryId: 1,
        price: 200,
        description:
          "Savourez une cuisine française élégante et innovante dans un cadre somptueux à l'hôtel Four Seasons George V. Une expérience gastronomique de luxe avec un service impeccable.",
        location: '31 Avenue George V, 75008 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3018 48.8675)'), 4326)"),
        latitude: 48.8675,
        longitude: 2.3018,
      },
      {
        id: 4,
        userId: 1,
        title: 'Soirée Rooftop Paris',
        categoryId: 2,
        price: 50,
        description:
          "Venez profiter d'une soirée inoubliable sur un rooftop avec une vue panoramique sur la ville de Paris. Musique live, DJ, cocktails et bonne ambiance garantis.",
        location: '10 Rue Oberkampf, 75011 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3708 48.8662)'), 4326)"),
        latitude: 48.8662,
        longitude: 2.3708,
      },
      {
        id: 5,
        userId: 1,
        title: 'Soirée Salsa à La Pachanga',
        categoryId: 2,
        price: 30,
        description:
          "Rejoignez-nous pour une soirée salsa endiablée à La Pachanga. Cours de danse, musique latine et ambiance festive jusqu'au bout de la nuit.",
        location: '8 Rue Vandamme, 75014 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3211 48.8371)'), 4326)"),
        latitude: 48.8371,
        longitude: 2.3211,
      },
      {
        id: 6,
        userId: 1,
        title: 'Soirée Jazz au Duc des Lombards',
        categoryId: 2,
        price: 40,
        description:
          "Passez une soirée inoubliable au rythme du jazz dans l'un des clubs les plus réputés de Paris. Musiciens talentueux, cocktails et ambiance feutrée.",
        location: '42 Rue des Lombards, 75001 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3470 48.8601)'), 4326)"),
        latitude: 48.8601,
        longitude: 2.347,
      },
      {
        id: 7,
        userId: 1,
        title: 'Supermarché Carrefour',
        categoryId: 3,
        price: 0,
        description:
          'Faites vos courses dans votre supermarché Carrefour préféré. Produits frais, épicerie, et tout ce dont vous avez besoin pour votre quotidien.',
        location: '10 Avenue de France, 75013 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3745 48.8297)'), 4326)"),
        latitude: 48.8297,
        longitude: 2.3745,
      },
      {
        id: 8,
        userId: 1,
        title: 'Supermarché Monoprix',
        categoryId: 3,
        price: 0,
        description:
          'Retrouvez tout ce dont vous avez besoin chez Monoprix. Des produits frais et de qualité pour vos courses quotidiennes.',
        location: '35 Boulevard Saint-Michel, 75005 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3431 48.8506)'), 4326)"),
        latitude: 48.8506,
        longitude: 2.3431,
      },
      {
        id: 9,
        userId: 1,
        title: 'Supermarché Franprix',
        categoryId: 3,
        price: 0,
        description:
          'Franprix, votre supermarché de proximité, vous offre une large gamme de produits pour tous vos besoins quotidiens.',
        location: '22 Rue de la Victoire, 75009 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3385 48.8747)'), 4326)"),
        latitude: 48.8747,
        longitude: 2.3385,
      },
      {
        id: 10,
        userId: 1,
        title: "Restaurant L'Arpège",
        categoryId: 1,
        price: 250,
        description:
          "Découvrez la cuisine végétarienne raffinée d'Alain Passard dans ce restaurant trois étoiles Michelin. Une expérience culinaire unique.",
        location: '84 Rue de Varenne, 75007 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3192 48.8563)'), 4326)"),
        latitude: 48.8563,
        longitude: 2.3192,
      },
      {
        id: 11,
        userId: 1,
        title: 'Restaurant Epicure',
        categoryId: 1,
        price: 300,
        description:
          'Savourez une cuisine française de haute gastronomie dans un cadre élégant et luxueux au Bristol Paris. Un voyage culinaire exceptionnel.',
        location: '112 Rue du Faubourg Saint-Honoré, 75008 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3161 48.8719)'), 4326)"),
        latitude: 48.8719,
        longitude: 2.3161,
      },
      {
        id: 12,
        userId: 1,
        title: 'Soirée Karaoké au BAM Karaoké Box',
        categoryId: 2,
        price: 20,
        description:
          "Chantez vos chansons préférées lors d'une soirée karaoké au BAM Karaoké Box. Des cabines privées pour une expérience inoubliable.",
        location: '50 Avenue de la République, 75011 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3701 48.8651)'), 4326)"),
        latitude: 48.8651,
        longitude: 2.3701,
      },
      {
        id: 13,
        userId: 1,
        title: 'Soirée Cinéma en Plein Air',
        categoryId: 2,
        price: 15,
        description:
          "Profitez d'une soirée cinéma en plein air avec une sélection de films classiques et modernes. Apportez votre couverture et installez-vous confortablement sous les étoiles.",
        location: 'Parc de la Villette, 75019 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3934 48.8895)'), 4326)"),
        latitude: 48.8895,
        longitude: 2.3934,
      },
      {
        id: 14,
        userId: 1,
        title: 'Soirée Techno au Rex Club',
        categoryId: 2,
        price: 35,
        description:
          "Dansez toute la nuit au son de la musique techno dans l'un des clubs les plus emblématiques de Paris. Ambiance électrisante et DJs renommés.",
        location: '5 Boulevard Poissonnière, 75002 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3486 48.8712)'), 4326)"),
        latitude: 48.8712,
        longitude: 2.3486,
      },
      {
        id: 15,
        userId: 1,
        title: 'Supermarché Leclerc',
        categoryId: 3,
        price: 0,
        description:
          'Leclerc, votre supermarché, vous propose une large gamme de produits alimentaires et non alimentaires à des prix compétitifs.',
        location: '15 Rue de Châteaudun, 75009 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3415 48.8769)'), 4326)"),
        latitude: 48.8769,
        longitude: 2.3415,
      },

      {
        id: 16,
        userId: 1,
        title: 'Restaurant Guy Savoy',
        categoryId: 1,
        price: 280,
        description:
          'Vivez une expérience culinaire unique dans le restaurant trois étoiles Michelin de Guy Savoy. Une cuisine française raffinée et inventive.',
        location: 'Monnaie de Paris, 11 Quai de Conti, 75006 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3398 48.8565)'), 4326)"),
        latitude: 48.8565,
        longitude: 2.3398,
      },
      {
        id: 17,
        userId: 1,
        title: 'Restaurant Alain Ducasse au Plaza Athénée',
        categoryId: 1,
        price: 320,
        description:
          'Dégustez la haute cuisine française dans un cadre élégant et raffiné au Plaza Athénée. Un voyage culinaire inoubliable signé Alain Ducasse.',
        location: '25 Avenue Montaigne, 75008 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3038 48.8668)'), 4326)"),
        latitude: 48.8668,
        longitude: 2.3038,
      },
      {
        id: 18,
        userId: 1,
        title: 'Soirée Rock à La Maroquinerie',
        categoryId: 2,
        price: 25,
        description:
          'Venez assister à une soirée rock à La Maroquinerie avec des performances live de groupes émergents et de talents locaux.',
        location: '23 Rue Boyer, 75020 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3875 48.8709)'), 4326)"),
        latitude: 48.8709,
        longitude: 2.3875,
      },
      {
        id: 19,
        userId: 1,
        title: 'Soirée Stand-up Comedy au Jamel Comedy Club',
        categoryId: 2,
        price: 20,
        description:
          "Riez aux éclats lors d'une soirée stand-up au Jamel Comedy Club avec des humoristes talentueux et des performances hilarantes.",
        location: '42 Boulevard Bonne Nouvelle, 75010 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3490 48.8702)'), 4326)"),
        latitude: 48.8702,
        longitude: 2.349,
      },
    ])
  }
}
