import Post from '#models/post'
import { BaseSeeder } from '@adonisjs/lucid/seeders'
import db from '@adonisjs/lucid/services/db'
export default class extends BaseSeeder {
  async run() {
    await Post.createMany([
      {
        id: 1,
        userId: 1,
        title: 'Restaurant Le Jules Verne',
        categoryId: 1,
        price: 120,
        description:
          "Dînez dans ce restaurant gastronomique avec une vue imprenable sur Paris, situé au deuxième étage de la Tour Eiffel. Profitez d'une cuisine raffinée et innovante, créée par des chefs de renom, tout en admirant la ville lumière.",
        location: 'Tour Eiffel, 2nd floor, Avenue Gustave Eiffel, 75007 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.294844 48.857739)'), 4326)"),
        latitude: 48.857739,
        longitude: 2.294844,
      },
      {
        id: 2,
        userId: 1,
        title: "Restaurant L'Atelier de Joël Robuchon",
        categoryId: 1,
        price: 150,
        description:
          "Découvrez la cuisine créative et savoureuse de Joël Robuchon dans un cadre élégant et moderne. Profitez d'un repas gastronomique inoubliable préparé avec des ingrédients de la plus haute qualité.",
        location: '5 Rue de Montalembert, 75007 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3265 48.8556)'), 4326)"),
        latitude: 48.8556,
        longitude: 2.3265,
      },
      {
        id: 3,
        userId: 1,
        title: 'Restaurant Le Cinq',
        categoryId: 1,
        price: 200,
        description:
          "Savourez une cuisine française élégante et innovante dans un cadre somptueux à l'hôtel Four Seasons George V. Une expérience gastronomique de luxe avec un service impeccable.",
        location: '31 Avenue George V, 75008 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3018 48.8675)'), 4326)"),
        latitude: 48.8675,
        longitude: 2.3018,
      },
      {
        id: 4,
        userId: 1,
        title: 'Soirée Rooftop Paris',
        categoryId: 2,
        price: 50,
        description:
          "Venez profiter d'une soirée inoubliable sur un rooftop avec une vue panoramique sur la ville de Paris. Musique live, DJ, cocktails et bonne ambiance garantis.",
        location: '10 Rue Oberkampf, 75011 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3708 48.8662)'), 4326)"),
        latitude: 48.8662,
        longitude: 2.3708,
      },
      {
        id: 5,
        userId: 1,
        title: 'Soirée Salsa à La Pachanga',
        categoryId: 2,
        price: 30,
        description:
          "Rejoignez-nous pour une soirée salsa endiablée à La Pachanga. Cours de danse, musique latine et ambiance festive jusqu'au bout de la nuit.",
        location: '8 Rue Vandamme, 75014 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3211 48.8371)'), 4326)"),
        latitude: 48.8371,
        longitude: 2.3211,
      },
      {
        id: 6,
        userId: 1,
        title: 'Soirée Jazz au Duc des Lombards',
        categoryId: 2,
        price: 40,
        description:
          "Passez une soirée inoubliable au rythme du jazz dans l'un des clubs les plus réputés de Paris. Musiciens talentueux, cocktails et ambiance feutrée.",
        location: '42 Rue des Lombards, 75001 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3470 48.8601)'), 4326)"),
        latitude: 48.8601,
        longitude: 2.347,
      },
      {
        id: 7,
        userId: 1,
        title: 'Supermarché Carrefour',
        categoryId: 3,
        price: 0,
        description:
          'Faites vos courses dans votre supermarché Carrefour préféré. Produits frais, épicerie, et tout ce dont vous avez besoin pour votre quotidien.',
        location: '10 Avenue de France, 75013 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3745 48.8297)'), 4326)"),
        latitude: 48.8297,
        longitude: 2.3745,
      },
      {
        id: 8,
        userId: 1,
        title: 'Supermarché Monoprix',
        categoryId: 3,
        price: 0,
        description:
          'Retrouvez tout ce dont vous avez besoin chez Monoprix. Des produits frais et de qualité pour vos courses quotidiennes.',
        location: '35 Boulevard Saint-Michel, 75005 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3431 48.8506)'), 4326)"),
        latitude: 48.8506,
        longitude: 2.3431,
      },
      {
        id: 9,
        userId: 1,
        title: 'Supermarché Franprix',
        categoryId: 3,
        price: 0,
        description:
          'Franprix, votre supermarché de proximité, vous offre une large gamme de produits pour tous vos besoins quotidiens.',
        location: '22 Rue de la Victoire, 75009 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3385 48.8747)'), 4326)"),
        latitude: 48.8747,
        longitude: 2.3385,
      },
      {
        id: 10,
        userId: 1,
        title: "Restaurant L'Arpège",
        categoryId: 1,
        price: 250,
        description:
          "Découvrez la cuisine végétarienne raffinée d'Alain Passard dans ce restaurant trois étoiles Michelin. Une expérience culinaire unique.",
        location: '84 Rue de Varenne, 75007 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3192 48.8563)'), 4326)"),
        latitude: 48.8563,
        longitude: 2.3192,
      },
      {
        id: 11,
        userId: 1,
        title: 'Restaurant Epicure',
        categoryId: 1,
        price: 300,
        description:
          'Savourez une cuisine française de haute gastronomie dans un cadre élégant et luxueux au Bristol Paris. Un voyage culinaire exceptionnel.',
        location: '112 Rue du Faubourg Saint-Honoré, 75008 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3161 48.8719)'), 4326)"),
        latitude: 48.8719,
        longitude: 2.3161,
      },
      {
        id: 12,
        userId: 1,
        title: 'Soirée Karaoké au BAM Karaoké Box',
        categoryId: 2,
        price: 20,
        description:
          "Chantez vos chansons préférées lors d'une soirée karaoké au BAM Karaoké Box. Des cabines privées pour une expérience inoubliable.",
        location: '50 Avenue de la République, 75011 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3701 48.8651)'), 4326)"),
        latitude: 48.8651,
        longitude: 2.3701,
      },
      {
        id: 13,
        userId: 1,
        title: 'Soirée Cinéma en Plein Air',
        categoryId: 2,
        price: 15,
        description:
          "Profitez d'une soirée cinéma en plein air avec une sélection de films classiques et modernes. Apportez votre couverture et installez-vous confortablement sous les étoiles.",
        location: 'Parc de la Villette, 75019 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3934 48.8895)'), 4326)"),
        latitude: 48.8895,
        longitude: 2.3934,
      },
      {
        id: 14,
        userId: 1,
        title: 'Soirée Techno au Rex Club',
        categoryId: 2,
        price: 35,
        description:
          "Dansez toute la nuit au son de la musique techno dans l'un des clubs les plus emblématiques de Paris. Ambiance électrisante et DJs renommés.",
        location: '5 Boulevard Poissonnière, 75002 Paris, France',
        geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3486 48.8712)'), 4326)"),
        latitude: 48.8712,
        longitude: 2.3486,
      },
      // {
      //   id: 15,
      //   userId: 1,
      //   title: 'Supermarché Leclerc',
      //   categoryId: 3,
      //   price: 0,
      //   description:
      //     'Leclerc, votre supermarché, vous propose une large gamme de produits alimentaires et non alimentaires à des prix compétitifs.',
      //   location: '15 Rue de Châteaudun, 75009 Paris, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3415 48.8769)'), 4326)"),
      //   latitude: 48.8769,
      //   longitude: 2.3415,
      // },
      // {
      //   id: 16,
      //   userId: 1,
      //   title: 'Supermarché Intermarché',
      //   categoryId: 3,
      //   price: 0,
      //   description:
      //     "Faites vos courses à Intermarché et profitez d'une large sélection de produits frais, épicerie, et bien plus encore.",
      //   location: '25 Rue de la Chapelle, 75018 Paris, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3613 48.8976)'), 4326)"),
      //   latitude: 48.8976,
      //   longitude: 2.3613,
      // },
      // {
      //   id: 17,
      //   userId: 1,
      //   title: 'Restaurant Guy Savoy',
      //   categoryId: 1,
      //   price: 280,
      //   description:
      //     'Vivez une expérience culinaire unique dans le restaurant trois étoiles Michelin de Guy Savoy. Une cuisine française raffinée et inventive.',
      //   location: 'Monnaie de Paris, 11 Quai de Conti, 75006 Paris, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3398 48.8565)'), 4326)"),
      //   latitude: 48.8565,
      //   longitude: 2.3398,
      // },
      // {
      //   id: 18,
      //   userId: 1,
      //   title: 'Restaurant Alain Ducasse au Plaza Athénée',
      //   categoryId: 1,
      //   price: 320,
      //   description:
      //     'Dégustez la haute cuisine française dans un cadre élégant et raffiné au Plaza Athénée. Un voyage culinaire inoubliable signé Alain Ducasse.',
      //   location: '25 Avenue Montaigne, 75008 Paris, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3038 48.8668)'), 4326)"),
      //   latitude: 48.8668,
      //   longitude: 2.3038,
      // },
      // {
      //   id: 19,
      //   userId: 1,
      //   title: 'Soirée Rock à La Maroquinerie',
      //   categoryId: 2,
      //   price: 25,
      //   description:
      //     'Venez assister à une soirée rock à La Maroquinerie avec des performances live de groupes émergents et de talents locaux.',
      //   location: '23 Rue Boyer, 75020 Paris, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3875 48.8709)'), 4326)"),
      //   latitude: 48.8709,
      //   longitude: 2.3875,
      // },
      // {
      //   id: 20,
      //   userId: 1,
      //   title: 'Soirée Stand-up Comedy au Jamel Comedy Club',
      //   categoryId: 2,
      //   price: 20,
      //   description:
      //     "Riez aux éclats lors d'une soirée stand-up au Jamel Comedy Club avec des humoristes talentueux et des performances hilarantes.",
      //   location: '42 Boulevard Bonne Nouvelle, 75010 Paris, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(2.3490 48.8702)'), 4326)"),
      //   latitude: 48.8702,
      //   longitude: 2.349,
      // },

      // {
      //   id: 21,
      //   userId: 1,
      //   title: 'Restaurant Chez Fonfon',
      //   categoryId: 1,
      //   price: 80,
      //   description:
      //     'Découvrez la cuisine traditionnelle marseillaise dans ce restaurant situé au Vallon des Auffes.',
      //   location: '140 Rue du Vallon des Auffes, 13007 Marseille, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(5.3558 43.2844)'), 4326)"),
      //   latitude: 43.2844,
      //   longitude: 5.3558,
      // },
      // {
      //   id: 22,
      //   userId: 1,
      //   title: 'Soirée au R2 Rooftop',
      //   categoryId: 2,
      //   price: 50,
      //   description:
      //     "Venez profiter d'une soirée inoubliable sur le rooftop avec une vue panoramique sur Marseille.",
      //   location: '9 Quai du Lazaret, 13002 Marseille, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(5.3656 43.3007)'), 4326)"),
      //   latitude: 43.3007,
      //   longitude: 5.3656,
      // },
      // {
      //   id: 23,
      //   userId: 1,
      //   title: 'Supermarché Carrefour',
      //   categoryId: 3,
      //   price: 0,
      //   description: 'Faites vos courses dans votre supermarché Carrefour préféré.',
      //   location: 'Le Merlan, 13014 Marseille, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(5.4043 43.3281)'), 4326)"),
      //   latitude: 43.3281,
      //   longitude: 5.4043,
      // },
      // {
      //   id: 24,
      //   userId: 1,
      //   title: 'Restaurant Le Miramar',
      //   categoryId: 1,
      //   price: 90,
      //   description: 'Savourez une bouillabaisse traditionnelle au restaurant Le Miramar.',
      //   location: '12 Quai du Port, 13002 Marseille, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(5.3672 43.2965)'), 4326)"),
      //   latitude: 43.2965,
      //   longitude: 5.3672,
      // },
      // {
      //   id: 25,
      //   userId: 1,
      //   title: 'Soirée Jazz au Jam',
      //   categoryId: 2,
      //   price: 40,
      //   description: 'Passez une soirée au rythme du jazz dans ce club emblématique de Marseille.',
      //   location: '42 Rue des Trois Rois, 13006 Marseille, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(5.3819 43.2933)'), 4326)"),
      //   latitude: 43.2933,
      //   longitude: 5.3819,
      // },
      // {
      //   id: 26,
      //   userId: 1,
      //   title: 'Supermarché Monoprix',
      //   categoryId: 3,
      //   price: 0,
      //   description: 'Retrouvez tout ce dont vous avez besoin chez Monoprix.',
      //   location: '11 Avenue du Prado, 13006 Marseille, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(5.3839 43.2846)'), 4326)"),
      //   latitude: 43.2846,
      //   longitude: 5.3839,
      // },
      // {
      //   id: 27,
      //   userId: 1,
      //   title: "Restaurant L'Epuisette",
      //   categoryId: 1,
      //   price: 150,
      //   description:
      //     "Profitez d'une vue imprenable et d'une cuisine raffinée au restaurant L'Epuisette.",
      //   location: 'Vallon des Auffes, 13007 Marseille, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(5.3558 43.2837)'), 4326)"),
      //   latitude: 43.2837,
      //   longitude: 5.3558,
      // },
      // {
      //   id: 28,
      //   userId: 1,
      //   title: 'Soirée Salsa au Bazar',
      //   categoryId: 2,
      //   price: 30,
      //   description: 'Rejoignez-nous pour une soirée salsa au Bazar.',
      //   location: '90 Boulevard Longchamp, 13001 Marseille, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(5.3856 43.3058)'), 4326)"),
      //   latitude: 43.3058,
      //   longitude: 5.3856,
      // },
      // {
      //   id: 29,
      //   userId: 1,
      //   title: 'Supermarché Casino',
      //   categoryId: 3,
      //   price: 0,
      //   description: 'Faites vos courses au supermarché Casino.',
      //   location: '14 Rue Saint-Ferréol, 13001 Marseille, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(5.3772 43.2975)'), 4326)"),
      //   latitude: 43.2975,
      //   longitude: 5.3772,
      // },
      // {
      //   id: 30,
      //   userId: 1,
      //   title: 'Restaurant Les Trois Forts',
      //   categoryId: 1,
      //   price: 100,
      //   description: 'Savourez une cuisine raffinée avec vue sur le Vieux-Port de Marseille.',
      //   location: '36 Boulevard Charles Livon, 13007 Marseille, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(5.3609 43.2924)'), 4326)"),
      //   latitude: 43.2924,
      //   longitude: 5.3609,
      // },
      // {
      //   id: 31,
      //   userId: 1,
      //   title: 'Restaurant La Petite Maison',
      //   categoryId: 1,
      //   price: 120,
      //   description: 'Dégustez une cuisine niçoise authentique dans un cadre élégant.',
      //   location: '11 Rue Saint-François de Paule, 06300 Nice, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(7.2728 43.6950)'), 4326)"),
      //   latitude: 43.695,
      //   longitude: 7.2728,
      // },
      // {
      //   id: 32,
      //   userId: 1,
      //   title: 'Soirée au High Club',
      //   categoryId: 2,
      //   price: 40,
      //   description: 'Dansez toute la nuit au High Club avec les meilleurs DJs.',
      //   location: '45 Prom. des Anglais, 06000 Nice, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(7.2550 43.6956)'), 4326)"),
      //   latitude: 43.6956,
      //   longitude: 7.255,
      // },
      // {
      //   id: 33,
      //   userId: 1,
      //   title: 'Supermarché Carrefour',
      //   categoryId: 3,
      //   price: 0,
      //   description: 'Faites vos courses dans votre supermarché Carrefour préféré.',
      //   location: '16 Avenue Thiers, 06000 Nice, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(7.2621 43.7056)'), 4326)"),
      //   latitude: 43.7056,
      //   longitude: 7.2621,
      // },
      // {
      //   id: 34,
      //   userId: 1,
      //   title: 'Restaurant Le Chantecler',
      //   categoryId: 1,
      //   price: 180,
      //   description: 'Découvrez une cuisine gastronomique au restaurant Le Chantecler.',
      //   location: '37 Prom. des Anglais, 06000 Nice, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(7.2625 43.6955)'), 4326)"),
      //   latitude: 43.6955,
      //   longitude: 7.2625,
      // },
      // {
      //   id: 35,
      //   userId: 1,
      //   title: 'Soirée Jazz au Shapko',
      //   categoryId: 2,
      //   price: 25,
      //   description: 'Passez une soirée au rythme du jazz au Shapko.',
      //   location: '5 Rue Rossetti, 06300 Nice, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(7.2754 43.6984)'), 4326)"),
      //   latitude: 43.6984,
      //   longitude: 7.2754,
      // },
      // {
      //   id: 36,
      //   userId: 1,
      //   title: 'Supermarché Monoprix',
      //   categoryId: 3,
      //   price: 0,
      //   description: 'Retrouvez tout ce dont vous avez besoin chez Monoprix.',
      //   location: '17 Avenue Jean Médecin, 06000 Nice, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(7.2653 43.7012)'), 4326)"),
      //   latitude: 43.7012,
      //   longitude: 7.2653,
      // },
      // {
      //   id: 37,
      //   userId: 1,
      //   title: "Restaurant L'Aromate",
      //   categoryId: 1,
      //   price: 100,
      //   description: "Dégustez une cuisine créative et savoureuse au restaurant L'Aromate.",
      //   location: '20 Avenue Maréchal Foch, 06000 Nice, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(7.2695 43.7045)'), 4326)"),
      //   latitude: 43.7045,
      //   longitude: 7.2695,
      // },
      // {
      //   id: 38,
      //   userId: 1,
      //   title: 'Soirée Rock au Volume',
      //   categoryId: 2,
      //   price: 30,
      //   description: 'Assistez à une soirée rock au Volume avec des performances live.',
      //   location: '6 Rue Defly, 06000 Nice, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(7.2787 43.7013)'), 4326)"),
      //   latitude: 43.7013,
      //   longitude: 7.2787,
      // },
      // {
      //   id: 39,
      //   userId: 1,
      //   title: 'Supermarché Casino',
      //   categoryId: 3,
      //   price: 0,
      //   description: 'Faites vos courses au supermarché Casino.',
      //   location: '12 Avenue Félix Faure, 06000 Nice, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(7.2698 43.7002)'), 4326)"),
      //   latitude: 43.7002,
      //   longitude: 7.2698,
      // },
      // {
      //   id: 40,
      //   userId: 1,
      //   title: 'Restaurant JAN',
      //   categoryId: 1,
      //   price: 150,
      //   description:
      //     'Savourez une cuisine franco-sud-africaine étoilée au guide Michelin au restaurant JAN.',
      //   location: '12 Rue Lascaris, 06300 Nice, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(7.2832 43.6991)'), 4326)"),
      //   latitude: 43.6991,
      //   longitude: 7.2832,
      // },
      // {
      //   id: 41,
      //   userId: 1,
      //   title: 'Restaurant Paul Bocuse',
      //   categoryId: 1,
      //   price: 200,
      //   description:
      //     'Découvrez la cuisine légendaire du chef Paul Bocuse dans ce restaurant emblématique.',
      //   location: "40 Quai de la Plage, 69660 Collonges-au-Mont-d'Or, France",
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(4.8420 45.8084)'), 4326)"),
      //   latitude: 45.8084,
      //   longitude: 4.842,
      // },
      // {
      //   id: 42,
      //   userId: 1,
      //   title: 'Soirée au Sucre',
      //   categoryId: 2,
      //   price: 45,
      //   description:
      //     'Dansez toute la nuit sur le rooftop du Sucre avec une vue imprenable sur Lyon.',
      //   location: '50 Quai Rambaud, 69002 Lyon, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(4.8155 45.7411)'), 4326)"),
      //   latitude: 45.7411,
      //   longitude: 4.8155,
      // },
      // {
      //   id: 43,
      //   userId: 1,
      //   title: 'Supermarché Carrefour',
      //   categoryId: 3,
      //   price: 0,
      //   description: 'Faites vos courses dans votre supermarché Carrefour préféré.',
      //   location: '16 Rue de la République, 69002 Lyon, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(4.8357 45.7597)'), 4326)"),
      //   latitude: 45.7597,
      //   longitude: 4.8357,
      // },
      // {
      //   id: 44,
      //   userId: 1,
      //   title: 'Restaurant La Mère Brazier',
      //   categoryId: 1,
      //   price: 150,
      //   description: 'Savourez une cuisine lyonnaise raffinée au restaurant La Mère Brazier.',
      //   location: '12 Rue Royale, 69001 Lyon, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(4.8353 45.7689)'), 4326)"),
      //   latitude: 45.7689,
      //   longitude: 4.8353,
      // },
      // {
      //   id: 45,
      //   userId: 1,
      //   title: 'Soirée Jazz au Hot Club',
      //   categoryId: 2,
      //   price: 35,
      //   description: 'Passez une soirée au rythme du jazz au Hot Club de Lyon.',
      //   location: '26 Rue Lanterne, 69001 Lyon, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(4.8301 45.7666)'), 4326)"),
      //   latitude: 45.7666,
      //   longitude: 4.8301,
      // },
      // {
      //   id: 46,
      //   userId: 1,
      //   title: 'Supermarché Monoprix',
      //   categoryId: 3,
      //   price: 0,
      //   description: 'Retrouvez tout ce dont vous avez besoin chez Monoprix.',
      //   location: '29 Avenue Jean Jaurès, 69007 Lyon, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(4.8367 45.7493)'), 4326)"),
      //   latitude: 45.7493,
      //   longitude: 4.8367,
      // },
      // {
      //   id: 47,
      //   userId: 1,
      //   title: 'Restaurant Le Neuvième Art',
      //   categoryId: 1,
      //   price: 180,
      //   description: 'Dégustez une cuisine innovante et élégante au restaurant Le Neuvième Art.',
      //   location: '173 Rue Cuvier, 69006 Lyon, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(4.8495 45.7717)'), 4326)"),
      //   latitude: 45.7717,
      //   longitude: 4.8495,
      // },
      // {
      //   id: 48,
      //   userId: 1,
      //   title: 'Soirée Salsa au Ninkasi',
      //   categoryId: 2,
      //   price: 30,
      //   description: 'Rejoignez-nous pour une soirée salsa au Ninkasi.',
      //   location: '267 Rue Marcel Mérieux, 69007 Lyon, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(4.8238 45.7329)'), 4326)"),
      //   latitude: 45.7329,
      //   longitude: 4.8238,
      // },
      // {
      //   id: 49,
      //   userId: 1,
      //   title: 'Supermarché Auchan',
      //   categoryId: 3,
      //   price: 0,
      //   description: 'Faites vos courses au supermarché Auchan.',
      //   location: '52 Avenue Franklin Roosevelt, 69008 Lyon, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(4.8726 45.7429)'), 4326)"),
      //   latitude: 45.7429,
      //   longitude: 4.8726,
      // },
      // {
      //   id: 50,
      //   userId: 1,
      //   title: 'Restaurant Takao Takano',
      //   categoryId: 1,
      //   price: 130,
      //   description:
      //     'Savourez une cuisine franco-japonaise étoilée au guide Michelin au restaurant Takao Takano.',
      //   location: '33 Rue Malesherbes, 69006 Lyon, France',
      //   geoloc: db.raw("ST_SetSRID(ST_GeomFromText('POINT(4.8494 45.7720)'), 4326)"),
      //   latitude: 45.772,
      //   longitude: 4.8494,
      // },
    ])
  }
}
