version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: frienddly_app
    ports:
      - '${APP_PORT:-3333}:3333'
    environment:
      APP_KEY: '${APP_KEY}'
      NODE_ENV: '${NODE_ENV:-development}'
      DB_CONNECTION: pg
      DB_HOST: pgsql
      DB_PORT: '${DB_PORT:-5432}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD:-secret}'
      DB_DATABASE: '${DB_DATABASE:-default}'
    volumes:
      - '.:/app'
      - 'node_modules:/app/node_modules'
      - 'uploads:/app/uploads'
      - 'logs:/app/logs'
    networks:
      - sail
    depends_on:
      - pgsql

  pgsql:
    image: 'postgres:15'
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE:-default}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'sailpgsql:/var/lib/postgresql/data'
    networks:
      - sail
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE:-default}', '-U', '${DB_USER}']
      retries: 3
      timeout: 5s

networks:
  sail:
    driver: bridge

volumes:
  sailpgsql:
  node_modules:
  uploads:
  logs:
