enum NotificationType {
  FRIENDSHIP_REQUEST = 'FRIENDSHIP_REQUEST',
  FRIENDSHIP_ACCEPTED = 'FRIENDSHIP_ACCEPTED',
  FRIENDSHIP_REJECTED = 'FRIENDSHIP_REJECTED',
  MESSAGE = 'MESSAGE',
  LIKE = 'LIKE',
  COMMENT = 'COMMENT',
  SHARE = 'SHARE',
  POST = 'POST',
  GROUP = 'GROUP',
  EVENT = 'EVENT',
}

export default NotificationType
